export const TYPE_CHANGE_SUCCESS = 'TYPE_CHANGE_SUCCESS'
export const TYPE_CHANGE_ERROR = 'TYPE_CHANGE_ERROR'

export const IP_CHANGE_SUCCESS = 'IP_DECIMAL_CHANGE_SUCCESS'
export const IP_CHANGE_ERROR = 'IP_DECIMAL_CHANGE_ERROR'

