export const TYPE_CHANGE_SUCCESS = 'TYPE_CHANGE_SUCCESS';
export const TYPE_CHANGE_ERROR = 'TYPE_CHANGE_ERROR';

export const IP_CHANGE_SUCCESS = 'IP_CHANGE_SUCCESS';
export const IP_CHANGE_ERROR = 'IP_CHANGE_ERROR';

export const MASK_LENGTH_REQUEST_SUCCESS = 'MASK_LENGTH_REQUEST_SUCCESS';
export const MASK_LENGTH_REQUEST_ERROR = 'MASK_LENGTH_REQUEST_ERROR';

export const RESET_REQUEST_SUCCESS = 'RESET_REQUEST_SUCCESS';
export const RESET_REQUEST_ERROR = 'RESET_REQUEST_ERROR';